
package org.apache.jackrabbit.cmis.ws.repository;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.1.3
 * Thu Dec 11 22:50:43 CET 2008
 * Generated source version: 2.1.3
 * 
 */

@WebFault(name = "invalidArgumentException", targetNamespace = "http://www.cmis.org/2008/05")
public class InvalidArgumentException extends Exception {
    public static final long serialVersionUID = 20081211225043L;
    
    private org.apache.jackrabbit.cmis.ws.repository.InvalidArgumentExceptionType invalidArgumentException;

    public InvalidArgumentException() {
        super();
    }
    
    public InvalidArgumentException(String message) {
        super(message);
    }
    
    public InvalidArgumentException(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidArgumentException(String message, org.apache.jackrabbit.cmis.ws.repository.InvalidArgumentExceptionType invalidArgumentException) {
        super(message);
        this.invalidArgumentException = invalidArgumentException;
    }

    public InvalidArgumentException(String message, org.apache.jackrabbit.cmis.ws.repository.InvalidArgumentExceptionType invalidArgumentException, Throwable cause) {
        super(message, cause);
        this.invalidArgumentException = invalidArgumentException;
    }

    public org.apache.jackrabbit.cmis.ws.repository.InvalidArgumentExceptionType getFaultInfo() {
        return this.invalidArgumentException;
    }
}
