
package org.apache.jackrabbit.cmis.ws.repository;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.1.3
 * Thu Dec 11 22:50:43 CET 2008
 * Generated source version: 2.1.3
 * 
 */

@WebFault(name = "objectNotFoundException", targetNamespace = "http://www.cmis.org/2008/05")
public class ObjectNotFoundException extends Exception {
    public static final long serialVersionUID = 20081211225043L;
    
    private org.apache.jackrabbit.cmis.ws.repository.ObjectNotFoundExceptionType objectNotFoundException;

    public ObjectNotFoundException() {
        super();
    }
    
    public ObjectNotFoundException(String message) {
        super(message);
    }
    
    public ObjectNotFoundException(String message, Throwable cause) {
        super(message, cause);
    }

    public ObjectNotFoundException(String message, org.apache.jackrabbit.cmis.ws.repository.ObjectNotFoundExceptionType objectNotFoundException) {
        super(message);
        this.objectNotFoundException = objectNotFoundException;
    }

    public ObjectNotFoundException(String message, org.apache.jackrabbit.cmis.ws.repository.ObjectNotFoundExceptionType objectNotFoundException, Throwable cause) {
        super(message, cause);
        this.objectNotFoundException = objectNotFoundException;
    }

    public org.apache.jackrabbit.cmis.ws.repository.ObjectNotFoundExceptionType getFaultInfo() {
        return this.objectNotFoundException;
    }
}
