
package org.apache.jackrabbit.cmis.ws.repository;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.1.3
 * Thu Dec 11 22:50:43 CET 2008
 * Generated source version: 2.1.3
 * 
 */

@WebFault(name = "operationNotSupportedException", targetNamespace = "http://www.cmis.org/2008/05")
public class OperationNotSupportedException extends Exception {
    public static final long serialVersionUID = 20081211225043L;
    
    private org.apache.jackrabbit.cmis.ws.repository.OperationNotSupportedExceptionType operationNotSupportedException;

    public OperationNotSupportedException() {
        super();
    }
    
    public OperationNotSupportedException(String message) {
        super(message);
    }
    
    public OperationNotSupportedException(String message, Throwable cause) {
        super(message, cause);
    }

    public OperationNotSupportedException(String message, org.apache.jackrabbit.cmis.ws.repository.OperationNotSupportedExceptionType operationNotSupportedException) {
        super(message);
        this.operationNotSupportedException = operationNotSupportedException;
    }

    public OperationNotSupportedException(String message, org.apache.jackrabbit.cmis.ws.repository.OperationNotSupportedExceptionType operationNotSupportedException, Throwable cause) {
        super(message, cause);
        this.operationNotSupportedException = operationNotSupportedException;
    }

    public org.apache.jackrabbit.cmis.ws.repository.OperationNotSupportedExceptionType getFaultInfo() {
        return this.operationNotSupportedException;
    }
}
