
package org.apache.jackrabbit.cmis.ws.repository;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.1.3
 * Thu Dec 11 22:50:43 CET 2008
 * Generated source version: 2.1.3
 * 
 */

@WebFault(name = "permissionDeniedException", targetNamespace = "http://www.cmis.org/2008/05")
public class PermissionDeniedException extends Exception {
    public static final long serialVersionUID = 20081211225043L;
    
    private org.apache.jackrabbit.cmis.ws.repository.PermissionDeniedExceptionType permissionDeniedException;

    public PermissionDeniedException() {
        super();
    }
    
    public PermissionDeniedException(String message) {
        super(message);
    }
    
    public PermissionDeniedException(String message, Throwable cause) {
        super(message, cause);
    }

    public PermissionDeniedException(String message, org.apache.jackrabbit.cmis.ws.repository.PermissionDeniedExceptionType permissionDeniedException) {
        super(message);
        this.permissionDeniedException = permissionDeniedException;
    }

    public PermissionDeniedException(String message, org.apache.jackrabbit.cmis.ws.repository.PermissionDeniedExceptionType permissionDeniedException, Throwable cause) {
        super(message, cause);
        this.permissionDeniedException = permissionDeniedException;
    }

    public org.apache.jackrabbit.cmis.ws.repository.PermissionDeniedExceptionType getFaultInfo() {
        return this.permissionDeniedException;
    }
}
