package org.apache.jackrabbit.cmis.ws.repository;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.1.3
 * Thu Dec 11 22:50:43 CET 2008
 * Generated source version: 2.1.3
 * 
 */
 
@WebService(targetNamespace = "http://www.cmis.org/2008/05", name = "RepositoryServicePort")
@XmlSeeAlso({ObjectFactory.class})
public interface RepositoryServicePort {

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getTypeDefinitionResponse", targetNamespace = "http://www.cmis.org/2008/05", partName = "parameters")
    @WebMethod
    public GetTypeDefinitionResponse getTypeDefinition(
        @WebParam(partName = "parameters", name = "getTypeDefinition", targetNamespace = "http://www.cmis.org/2008/05")
        GetTypeDefinition parameters
    ) throws PermissionDeniedException, UpdateConflictException, ObjectNotFoundException, OperationNotSupportedException, TypeNotFoundException, InvalidArgumentException, RuntimeException, ConstraintViolationException;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getRepositoryInfoResponse", targetNamespace = "http://www.cmis.org/2008/05", partName = "parameters")
    @WebMethod
    public CmisRepositoryInfoType getRepositoryInfo(
        @WebParam(partName = "parameters", name = "getRepositoryInfo", targetNamespace = "http://www.cmis.org/2008/05")
        GetRepositoryInfo parameters
    ) throws PermissionDeniedException, UpdateConflictException, ObjectNotFoundException, OperationNotSupportedException, InvalidArgumentException, RuntimeException, ConstraintViolationException;

    @ResponseWrapper(localName = "getRepositoriesResponse", targetNamespace = "http://www.cmis.org/2008/05", className = "org.apache.jackrabbit.cmis.ws.repository.GetRepositoriesResponse")
    @RequestWrapper(localName = "getRepositories", targetNamespace = "http://www.cmis.org/2008/05", className = "org.apache.jackrabbit.cmis.ws.repository.GetRepositories")
    @WebResult(name = "repository", targetNamespace = "http://www.cmis.org/2008/05")
    @WebMethod
    public java.util.List<org.apache.jackrabbit.cmis.ws.repository.CmisRepositoryEntryType> getRepositories() throws PermissionDeniedException, UpdateConflictException, OperationNotSupportedException, InvalidArgumentException, RuntimeException;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getTypesResponse", targetNamespace = "http://www.cmis.org/2008/05", partName = "parameters")
    @WebMethod
    public GetTypesResponse getTypes(
        @WebParam(partName = "parameters", name = "getTypes", targetNamespace = "http://www.cmis.org/2008/05")
        GetTypes parameters
    ) throws PermissionDeniedException, UpdateConflictException, ObjectNotFoundException, OperationNotSupportedException, InvalidArgumentException, RuntimeException, ConstraintViolationException;
}
