
package org.apache.jackrabbit.cmis.ws.repository;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.1.3
 * Thu Dec 11 22:50:43 CET 2008
 * Generated source version: 2.1.3
 * 
 */

@WebFault(name = "runtimeException", targetNamespace = "http://www.cmis.org/2008/05")
public class RuntimeException extends Exception {
    public static final long serialVersionUID = 20081211225043L;
    
    private org.apache.jackrabbit.cmis.ws.repository.RuntimeExceptionType runtimeException;

    public RuntimeException() {
        super();
    }
    
    public RuntimeException(String message) {
        super(message);
    }
    
    public RuntimeException(String message, Throwable cause) {
        super(message, cause);
    }

    public RuntimeException(String message, org.apache.jackrabbit.cmis.ws.repository.RuntimeExceptionType runtimeException) {
        super(message);
        this.runtimeException = runtimeException;
    }

    public RuntimeException(String message, org.apache.jackrabbit.cmis.ws.repository.RuntimeExceptionType runtimeException, Throwable cause) {
        super(message, cause);
        this.runtimeException = runtimeException;
    }

    public org.apache.jackrabbit.cmis.ws.repository.RuntimeExceptionType getFaultInfo() {
        return this.runtimeException;
    }
}
