
package org.apache.jackrabbit.cmis.ws.repository;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.1.3
 * Thu Dec 11 22:50:43 CET 2008
 * Generated source version: 2.1.3
 * 
 */

@WebFault(name = "typeNotFoundException", targetNamespace = "http://www.cmis.org/2008/05")
public class TypeNotFoundException extends Exception {
    public static final long serialVersionUID = 20081211225043L;
    
    private org.apache.jackrabbit.cmis.ws.repository.TypeNotFoundExceptionType typeNotFoundException;

    public TypeNotFoundException() {
        super();
    }
    
    public TypeNotFoundException(String message) {
        super(message);
    }
    
    public TypeNotFoundException(String message, Throwable cause) {
        super(message, cause);
    }

    public TypeNotFoundException(String message, org.apache.jackrabbit.cmis.ws.repository.TypeNotFoundExceptionType typeNotFoundException) {
        super(message);
        this.typeNotFoundException = typeNotFoundException;
    }

    public TypeNotFoundException(String message, org.apache.jackrabbit.cmis.ws.repository.TypeNotFoundExceptionType typeNotFoundException, Throwable cause) {
        super(message, cause);
        this.typeNotFoundException = typeNotFoundException;
    }

    public org.apache.jackrabbit.cmis.ws.repository.TypeNotFoundExceptionType getFaultInfo() {
        return this.typeNotFoundException;
    }
}
