
package org.apache.jackrabbit.cmis.ws.repository;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.1.3
 * Thu Dec 11 22:50:43 CET 2008
 * Generated source version: 2.1.3
 * 
 */

@WebFault(name = "updateConflictException", targetNamespace = "http://www.cmis.org/2008/05")
public class UpdateConflictException extends Exception {
    public static final long serialVersionUID = 20081211225043L;
    
    private org.apache.jackrabbit.cmis.ws.repository.UpdateConflictExceptionType updateConflictException;

    public UpdateConflictException() {
        super();
    }
    
    public UpdateConflictException(String message) {
        super(message);
    }
    
    public UpdateConflictException(String message, Throwable cause) {
        super(message, cause);
    }

    public UpdateConflictException(String message, org.apache.jackrabbit.cmis.ws.repository.UpdateConflictExceptionType updateConflictException) {
        super(message);
        this.updateConflictException = updateConflictException;
    }

    public UpdateConflictException(String message, org.apache.jackrabbit.cmis.ws.repository.UpdateConflictExceptionType updateConflictException, Throwable cause) {
        super(message, cause);
        this.updateConflictException = updateConflictException;
    }

    public org.apache.jackrabbit.cmis.ws.repository.UpdateConflictExceptionType getFaultInfo() {
        return this.updateConflictException;
    }
}
